### ISSUE TITLE
IR Compiler 

### ISSUE THREAD

**Issue by JimeFuture** [bnorm/kotlin-react-function#5]
I have some issues to get the IR Compiler working for a simple Project setup created with Intellj Idea template.
I'm quiet new in Kotlin and also with all the gradle setup because i try to switch from TS wit npm to Kotlin in the moment

here is the build.gradle.kts:
```
plugins {
    kotlin("js") version "1.4.10"
    id("com.bnorm.react.kotlin-react-function") version "0.2.0"
}
group = "me.jim"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
    jcenter()
    maven {
        url = uri("https://dl.bintray.com/kotlin/kotlinx")
    }
    maven {
        url = uri("https://dl.bintray.com/kotlin/kotlin-js-wrappers")
    }
}
dependencies {
    testImplementation(kotlin("test-js"))
    implementation(kotlin("stdlib-js"))
    implementation("org.jetbrains.kotlinx:kotlinx-html-js:0.7.2")
    implementation("org.jetbrains:kotlin-react:16.13.1-pre.110-kotlin-1.4.10")
    implementation("org.jetbrains:kotlin-react-dom:16.13.1-pre.110-kotlin-1.4.10")
    implementation("org.jetbrains:kotlin-styled:1.0.0-pre.110-kotlin-1.4.10")
    implementation("com.bnorm.react:kotlin-react-function:0.2.0")
}
kotlin {
    js(IR) {
        browser {
            binaries.executable()
            webpackTask {
                cssSupport.enabled = true
            }
            runTask {
                cssSupport.enabled = true
            }
            testTask {
                useKarma {
                    useChromeHeadless()
                    webpackConfig.cssSupport.enabled = true
                }
            }
        }
    }
}
```

And here is the resulting error stacktrace trying to run a build or the integrated BrowserDevelopmentRun:
```
Waiting for changes to input files of tasks... (ctrl-d to exit)
e: java.lang.IllegalStateException: Operation is unsupported
	at org.jetbrains.kotlin.ir.backend.js.lower.DescriptorlessIrFileSymbol.getDescriptor(MoveBodilessDeclarationsToSeparatePlace.kt:53)
	at org.jetbrains.kotlin.ir.backend.js.lower.DescriptorlessIrFileSymbol.getDescriptor(MoveBodilessDeclarationsToSeparatePlace.kt:47)
	at org.jetbrains.kotlin.ir.descriptors.WrappedClassDescriptor.getContainingDeclaration(WrappedDescriptors.kt:576)
	at org.jetbrains.kotlin.types.ErrorUtils.isError(ErrorUtils.java:547)
	at org.jetbrains.kotlin.resolve.DescriptorUtils.getFqNameSafeIfPossible(DescriptorUtils.java:99)
	at org.jetbrains.kotlin.resolve.DescriptorUtils.getFqName(DescriptorUtils.java:86)
	at org.jetbrains.kotlin.resolve.DescriptorUtils.getFqNameUnsafe(DescriptorUtils.java:117)
	at org.jetbrains.kotlin.resolve.DescriptorUtils.getFqNameSafe(DescriptorUtils.java:93)
	at org.jetbrains.kotlin.resolve.descriptorUtil.DescriptorUtilsKt.getFqNameSafe(DescriptorUtils.kt:56)
	at org.jetbrains.kotlin.backend.common.lower.matchers.FqNameMatcher.invoke(IrFunctionMatcher.kt:59)
	at org.jetbrains.kotlin.backend.common.lower.matchers.FqNameMatcher.invoke(IrFunctionMatcher.kt:54)
	at org.jetbrains.kotlin.backend.common.lower.matchers.IrFunctionMatcherContainer.invoke(IrFunctionMatcher.kt:85)
	at org.jetbrains.kotlin.backend.common.lower.matchers.IrFunctionMatcherContainer.invoke(IrFunctionMatcher.kt:63)
	at org.jetbrains.kotlin.backend.common.lower.matchers.SimpleCalleeMatcher.invoke(IrCallMatcher.kt:23)
	at org.jetbrains.kotlin.backend.common.lower.matchers.SimpleCalleeMatcher.invoke(IrCallMatcher.kt:17)
	at org.jetbrains.kotlin.backend.common.lower.matchers.IrCallMatcherContainer.invoke(IrCallMatcher.kt:69)
	at org.jetbrains.kotlin.backend.common.lower.matchers.IrCallMatcherContainer.invoke(IrCallMatcher.kt:46)
	at org.jetbrains.kotlin.backend.common.lower.loops.HeaderInfoFromCallHandler$DefaultImpls.matchIterable(HeaderInfo.kt:234)
	at org.jetbrains.kotlin.backend.common.lower.loops.ReversedHandler.matchIterable(ProgressionHandlers.kt:558)
	at org.jetbrains.kotlin.backend.common.lower.loops.ReversedHandler.matchIterable(ProgressionHandlers.kt:558)
	at org.jetbrains.kotlin.backend.common.lower.loops.HeaderInfoHandler$DefaultImpls.handle(HeaderInfo.kt:218)
	at org.jetbrains.kotlin.backend.common.lower.loops.HeaderInfoFromCallHandler$DefaultImpls.handle(HeaderInfo.kt)
	at org.jetbrains.kotlin.backend.common.lower.loops.ReversedHandler.handle(ProgressionHandlers.kt:558)
	at org.jetbrains.kotlin.backend.common.lower.loops.ReversedHandler.handle(ProgressionHandlers.kt:558)
	at org.jetbrains.kotlin.backend.common.lower.loops.HeaderInfoBuilder.visitCall(HeaderInfo.kt:275)
	at org.jetbrains.kotlin.backend.common.lower.loops.HeaderInfoBuilder.visitCall(HeaderInfo.kt:239)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:78)
	at org.jetbrains.kotlin.backend.common.lower.loops.HeaderProcessor.extractHeader(HeaderProcessor.kt:662)
	at org.jetbrains.kotlin.backend.common.lower.loops.RangeLoopTransformer.visitBlock(ForLoopsLowering.kt:150)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:128)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockImpl.accept(IrBlockImpl.kt:52)
	at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:28)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrContainerExpressionBase.transformChildren(IrContainerExpressionBase.kt:44)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:292)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildrenVoid(IrElementTransformerVoid.kt:287)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildren(IrElementTransformerVoid.kt:25)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:112)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitContainerExpression(IrElementTransformerVoid.kt:124)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:130)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:131)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCompositeImpl.accept(IrCompositeImpl.kt:46)
	at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:28)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrContainerExpressionBase.transformChildren(IrContainerExpressionBase.kt:44)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:292)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildrenVoid(IrElementTransformerVoid.kt:287)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildren(IrElementTransformerVoid.kt:25)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:112)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitContainerExpression(IrElementTransformerVoid.kt:124)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:130)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:131)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCompositeImpl.accept(IrCompositeImpl.kt:46)
	at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:28)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrMemberAccessExpressionBase.transformChildren(IrMemberAccessExpressionBase.kt:62)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallWithIndexedArgumentsBase.transformChildren(IrCallWithIndexedArgumentsBase.kt:68)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:292)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildrenVoid(IrElementTransformerVoid.kt:287)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildren(IrElementTransformerVoid.kt:25)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:112)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitMemberAccess(IrElementTransformerVoid.kt:166)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFunctionAccess(IrElementTransformerVoid.kt:169)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:172)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:173)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:78)
	at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:28)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallWithIndexedArgumentsBase.transformChildren(IrCallWithIndexedArgumentsBase.kt:70)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:292)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildrenVoid(IrElementTransformerVoid.kt:287)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildren(IrElementTransformerVoid.kt:25)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:112)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitMemberAccess(IrElementTransformerVoid.kt:166)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFunctionAccess(IrElementTransformerVoid.kt:169)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:172)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:173)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:78)
	at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:28)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrContainerExpressionBase.transformChildren(IrContainerExpressionBase.kt:44)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:292)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildrenVoid(IrElementTransformerVoid.kt:287)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildren(IrElementTransformerVoid.kt:25)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:112)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitContainerExpression(IrElementTransformerVoid.kt:124)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:130)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:131)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCompositeImpl.accept(IrCompositeImpl.kt:46)
	at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:28)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrContainerExpressionBase.transformChildren(IrContainerExpressionBase.kt:44)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:292)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildrenVoid(IrElementTransformerVoid.kt:287)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildren(IrElementTransformerVoid.kt:25)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:112)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitContainerExpression(IrElementTransformerVoid.kt:124)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:130)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:131)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitComposite(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCompositeImpl.accept(IrCompositeImpl.kt:46)
	at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:28)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrTypeOperatorCallImpl.transformChildren(IrTypeOperatorCallImpl.kt:75)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:292)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildrenVoid(IrElementTransformerVoid.kt:287)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildren(IrElementTransformerVoid.kt:25)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:112)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitTypeOperator(IrElementTransformerVoid.kt:218)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitTypeOperator(IrElementTransformerVoid.kt:219)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitTypeOperator(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrTypeOperatorCallImpl.accept(IrTypeOperatorCallImpl.kt:68)
	at org.jetbrains.kotlin.ir.expressions.IrExpression$DefaultImpls.transform(IrExpression.kt:28)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBase.transform(IrExpressionBase.kt:24)
	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockBodyImpl.transformChildren(IrBlockBodyImpl.kt:53)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:292)
	at org.jetbrains.kotlin.backend.common.lower.loops.ForLoopsLowering.lower(ForLoopsLowering.kt:102)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1$1.invoke(Lower.kt:138)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1$1.invoke(Lower.kt:117)
	at org.jetbrains.kotlin.ir.declarations.StageController$DefaultImpls.bodyLowering(PersistentApi.kt:31)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt$compile$1.bodyLowering(compiler.kt:50)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitBody(Lower.kt:137)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitBody(Lower.kt:117)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitBlockBody(IrElementVisitor.kt:48)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitBlockBody(Lower.kt:117)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitBlockBody(Lower.kt:117)
	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockBodyImpl.accept(IrBlockBodyImpl.kt:44)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFunctionBase.acceptChildren(IrFunctionBase.kt:143)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitDeclaration(Lower.kt:123)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitDeclaration(Lower.kt:117)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitFunction(IrElementVisitor.kt:33)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitFunction(Lower.kt:117)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitFunction(Lower.kt:117)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitSimpleFunction(IrElementVisitor.kt:34)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitSimpleFunction(Lower.kt:117)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitSimpleFunction(Lower.kt:117)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFunctionImpl.accept(IrFunctionImpl.kt:137)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitClass(Lower.kt:129)
	at org.jetbrains.kotlin.backend.common.LowerKt$runOnFilePostfix$$inlined$forEach$lambda$1.visitClass(Lower.kt:117)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.accept(IrClassImpl.kt:166)
	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix(Lower.kt:117)
	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix$default(Lower.kt:115)
	at org.jetbrains.kotlin.backend.common.BodyLoweringPass$DefaultImpls.lower(Lower.kt:65)
	at org.jetbrains.kotlin.backend.common.lower.loops.ForLoopsLowering.lower(ForLoopsLowering.kt:97)
	at org.jetbrains.kotlin.backend.common.LowerKt.lower(Lower.kt:68)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$makeIrModulePhase$1.invoke(PhaseBuilders.kt:240)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$makeIrModulePhase$1.invoke(PhaseBuilders.kt:233)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:30)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper$runBody$1.invoke(CompilerPhase.kt:128)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.downlevel(CompilerPhase.kt:24)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.runBody(CompilerPhase.kt:127)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedPhaseWrapper.invoke(CompilerPhase.kt:105)
	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:42)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile(compiler.kt:102)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile$default(compiler.kt:48)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:221)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:74)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:86)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1549)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

it would be nice if someone could help me with this issue. The kotlin-react-function annotation looks very helpfull for me and would save a lot time in further progress, but in the moment it is niot possible to run it.

**Comment by bnorm** [comment]
Thanks for the issue! The stacktrace doesn't indicate any direct problem with this plugin, but if you can provide more details about your project or even provide a sample project which reproduces the issue, I can hopefully dig into it further.

**Comment by bnorm** [comment]
Any updates on this @JimeFuture? If it helps you track down the offending code, this seems to be occurring around a for loop which might be iterating backwards? Here's the section of the stacktrace which seems to indicate that:

```
	at org.jetbrains.kotlin.backend.common.lower.loops.ReversedHandler.handle(ProgressionHandlers.kt:558)
	at org.jetbrains.kotlin.backend.common.lower.loops.ReversedHandler.handle(ProgressionHandlers.kt:558)
	at org.jetbrains.kotlin.backend.common.lower.loops.HeaderInfoBuilder.visitCall(HeaderInfo.kt:275)
	at org.jetbrains.kotlin.backend.common.lower.loops.HeaderInfoBuilder.visitCall(HeaderInfo.kt:239)
	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:78)
	at org.jetbrains.kotlin.backend.common.lower.loops.HeaderProcessor.extractHeader(HeaderProcessor.kt:662)
	at org.jetbrains.kotlin.backend.common.lower.loops.RangeLoopTransformer.visitBlock(ForLoopsLowering.kt:150)
```

**Comment by bnorm** [comment]
Without sample code there is nothing I can figure out from this stacktrace.
